read words from file
mauricioabreu/go-hangman pull request #12
Opened 2018-10-05 05:05 UTC by omurbekjk

Solves this issue https://github.com/mauricioabreu/go-hangman/issues/11

2018-10-05 11:24 UTC, pablodiehl approved these changes

2018-10-05 15:51 UTC, mauricioabreu requested changes
Thank you for your contribution. I noticed some relevant problems and listed them.
Can you check it? Again, thank you very much! I really appreciate your contribution. 👍

2018-10-05 15:51 UTC, mauricioabreu commented on words/words.txt
> +apple,
I think the file can be split by newlines instead of comma.

```
apple
banana
moose
```

And so on. What do you think?

2018-10-05 15:51 UTC, mauricioabreu commented on http/api.go
> +	b, err := ioutil.ReadFile("file.txt") // read words from file
Does it work? The file is `words/words.txt` and the file here is `file.txt`.

2018-10-08 03:28 UTC, omurbekjk commented
I fixed wrong file path

2018-10-09 00:52 UTC, mauricioabreu approved these changes
LGTM! :+1:  Thank you for your contribution

2018-10-09 00:53 UTC, merged